# Generated by Django 4.2.6 on 2023-10-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('dni', models.CharField(default='', max_length=10)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
