# Generated by Django 4.2.6 on 2023-11-08 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_users_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identificacion_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='updated_at',
        ),
    ]
