# Generated by Django 4.2.6 on 2023-11-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_users_created_at_users_delete_at_users_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identificacion_types',
            name='delete_at',
        ),
    ]
